import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docs: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Fondamenti di Python',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
          'fondamenti-di-python/programmare-in-python',
          ],
    },
    {
      type: 'category',
      label: 'Le basi del linguaggio',
      link: {
        type: 'doc', id: 'basi-del-linguaggio/index'
      },
      collapsed: true,
      items: [
        'basi-del-linguaggio/output',
        'basi-del-linguaggio/le-variabili',
        'basi-del-linguaggio/le-stringhe',
      ]
    },
  ],


};

export default sidebars;
